"""empty message

Revision ID: 13b00749b91b
Revises: 2869f629e8d9
Create Date: 2014-11-30 01:31:42.670112

"""

# revision identifiers, used by Alembic.
revision = '13b00749b91b'
down_revision = '2869f629e8d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
