"""empty message

Revision ID: 1a5d109155a0
Revises: 13b00749b91b
Create Date: 2014-11-30 01:36:36.223813

"""

# revision identifiers, used by Alembic.
revision = '1a5d109155a0'
down_revision = '13b00749b91b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
