"""empty message

Revision ID: 2869f629e8d9
Revises: 2b5758fd45ab
Create Date: 2014-11-29 23:09:35.832568

"""

# revision identifiers, used by Alembic.
revision = '2869f629e8d9'
down_revision = '2b5758fd45ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
